### ISSUE TITLE
Create ivp_a1 dictionary using ivp_a1 Json schema in cognitionexplorer

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/nacculator#6]
The form exported from redcap only give you key of the choice to a multiple-choice question, not the value of the key. We need to figure out whether to add the value of the key to our json file and how to implement it.

**Comment by JasonFHough** [comment]
See the following for reference:

https://github.com/utsw-bicf/cognitionexplorer/blob/7-a1_schema/src/encoded/tests/data/inserts/ivp_a1.json

**Comment by mingjiecn** [comment]
The csv(label) file contains both key and values, but the format can be different with the PDF design file that is used for json schema by @SenseCode . After discussion on 05/26/2020, we will use the csv(raw) file, which will only contain keys of questions. We will create a dictionary using json schema, then we can add the value of the keys into the json data file. 

We will start with ivp_a1 form since @SenseCode already has this schema in progress.
