### ISSUE TITLE
Create ivp_a1 json data file using all data in csv(raw) format in redcap

### ISSUE THREAD

**Issue by mingjiecn** [utsw-bicf/nacculator#9]
after discussion with @JasonFHough  on 05/26/2020, we will use Pandas as the library to convert from scv to json: https://pandas.pydata.org/docs/index.html
We will use report contains all data in scv raw format as our source data.
@JasonFHough will try to create ivp_a1 json data file first with only keys.
After the dictionary is created then we can create ivp_a1 json data file with keys and values that can be used in cognitionexplorer.

**Comment by JasonFHough** [comment]
Commit [`ae9bbfc2c701e581f4801df275d93c657697b227`](https://github.com/utsw-bicf/nacculator/commit/ae9bbfc2c701e581f4801df275d93c657697b227) outputs the ivp_a1 JSON file.

Awaiting proper dictionary containing actual keys/values corresponding to the a1 schema.
